### ISSUE TITLE
Transposed create() and update() methods

### ISSUE THREAD

**Issue by chris-roberts-ddi** [wpfeiffe-arbfile/mn-data#1]
Great examples!

I think in the CompanyController, your create() and update() methods are reversed:

create() -- should have the POST and not PUT, and should have the code currently in update()
update() -- should be with the PUT, and have the code currently in the create() method

**Comment by wpfeiffe-alternate** [comment]
Hah!  You are right on that.  I spend a lot of time reading up on correct methods for REST POST/PUT before realizing you were saying I just named the methods themselves backwards.  And I did it on all the Controllers.  Good catch! Fixed.
